name: Reproducer for multipass 4588
on:
  push:
    branch:
      - multipass-4588
  # Allows triggering the workflow manually from the Actions tab
  workflow_dispatch:
    inputs:
      enable_ssh_access:
        type: boolean
        description: "Enable ssh access"
        required: false
        default: false

jobs:
  brew:
    runs-on: macos-15-intel
    steps:
      - name: Check open ports
        run: |
          sudo lsof -i -n -P
      - name: Install Multipass
        run: |
          brew install --cask multipass
      - name: Print multipass log post install
        run: |
          sudo cat /Library/Logs/Multipass/multipassd.log
      - name: Increase logging level and restart multipassd
        run: |
          multipass_passphrase=$(uuidgen)
          multipass set local.passphrase=$multipass_passphrase
          sudo multipass authenticate $multipass_passphrase
          sudo su -m root -c 'launchctl unload /Library/LaunchDaemons/com.canonical.multipassd.plist'
          sed 's|<string>debug</string>|<string>trace</string>|' /Library/LaunchDaemons/com.canonical.multipassd.plist | sudo tee /Library/LaunchDaemons/com.canonical.multipassd.plist
          sudo su -m root -c 'launchctl load /Library/LaunchDaemons/com.canonical.multipassd.plist'
      - name: Wait until multipass is ready
        run: |
          for i in {1..120}; do
            if multipass list; then
              exit 0
            fi
          done
          echo "Multipass took over 2 minutes to start"
          exit 1
      - name: Authenticate root
        run: |
          multipass_passphrase=$(uuidgen)
          multipass set local.passphrase=$multipass_passphrase
          sudo multipass authenticate $multipass_passphrase
          for i in {1..120}; do
            if sudo multipass list; then
              exit 0
            fi
          done
          echo "Multipass took over 2 minutes to allow root access"
          exit 1
      - name: Print multipass log
        run: |
          sudo cat /Library/Logs/Multipass/multipassd.log
      - name: Check open ports
        run: |
          sudo lsof -i -n -P
      - name: Check running processes
        run: |
          ps -ef
      - name: Launch noble instance
        run: |
          multipass launch 24.04 --name test
      - name: Attempt to use instance
        run: |
          sudo multipass list
          sudo multipass exec test -- cat /etc/os-release
      - name: Show network access to instance
        if: ${{ always() }}
        run: |
          vm_ip=$(sudo multipass list --format json | jq -r '.list[] | select( .name == "test" ) | .ipv4[0]')
          ping -c 4 $vm_ip
          ssh -vv $vm_ip
      - name: Print multipass log
        if: ${{ always() }}
        run: |
          sudo cat /Library/Logs/Multipass/multipassd.log
      - name: Enable ssh access
        uses: mxschmitt/action-tmate@v3
        if: ${{ always() && inputs.enable_ssh_access }}
        with:
          limit-access-to-actor: true

